services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es_data:/usr/share/elasticsearch/data:Z
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.3
    container_name: logstash
    environment:
      - xpack.monitoring.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # restart: always
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:Z
    ports:
      - "5044:5044"  
      - "514:514"  
      - "5045:5045" 
      - "5046:5046" 
      - "9600:9600" 
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    container_name: kibana
    environment:
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTICSEARCH_HOSTS=http://192.168.1.104:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch


# volumes:
#   es_data:
#     driver: local

networks:
  elk:
    driver: bridge
